[package]
name = "pattie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
crossbeam = "0.8.1"
ndarray = { version = "0.15.3", features = ["rayon"] }
num = "0.4.0"
rayon = "1.5.1"
smallvec = { version = "1.7.0", features = ["const_generics", "union", "write"] }
tempfile = "3.2.0"
thiserror = "1.0.30"
